# Generated by Django 4.0.6 on 2022-09-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_choice2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice2',
            new_name='Choice',
        ),
    ]
